export { default as DashboardPage} from './DashboardPage'
export { default as UsersPage } from './UsersPage'
export { default as BookingPage } from './BookingPage'
export { default as CategoryPage } from './CategoryPage'
export { default as TourPage } from './TourPage'
export { default as TourActivePage } from './TourActivePage'
export { default as CommentPage } from './CommentPage'
export { default as NavigationBar} from '../../components/NavigationBar/NavigationBar'
export { default as getUsers} from '../../controllers/user'
export { default as CreateTour} from './CreateTours'
export { default as InputForm} from '../../components/InputForm'
export { default as MarkdownEditor} from '../../components/MarkdownEditor'